version: 2

models:
  - name: dim_metric_type
    description: "Dimension model for metric types."
    columns:
      - name: metric_type_key
        description: "Unique identifier for each record."
        tests:
          - unique
          - not_null

      - name: metric_type_id
        description: "Unique identifier for each metric type."

      - name: metric_type_name
        description: "Name of the metric type."
    
  - name: dim_sensor
    description: "Dimension model for sensors."
    columns:
      - name: sensor_key
        description: "Unique identifier for each record."
        tests:
          - unique
          - not_null

      - name: sensor_id
        description: "Unique identifier for each sensor."

      - name: sensor_type_id
        description: "Identifier for the type of sensor."
      
      - name: sensor_type_name
        description: "Name of the sensor type."
      
      - name: is_hive_level
        description: "Indicates if the sensor is at the hive level." 

      - name: hive_id
        description: "Identifier for the hive associated with the sensor."

      - name: status
        description: "Current status of the sensor."

      - name: installed_at
        description: "Timestamp when the sensor was installed."

      - name: valid_from
        description: "Timestamp indicating when the record became valid."

      - name: valid_to
        description: "Timestamp indicating when the record is no longer valid." 
  
      - name: is_current
        description: "Indicates if the record is the current version."
  
    

      